version: '2.4'

services:
  express:
    build: .
    init: true
    ports:
      - 3000:3000
    volumes:
      - .:/node/app
      - /node/app/node_modules
    environment:
      - DEBUG=sample-express:*

